[package]
name = "gcp-bigquery-client"
version = "0.13.0"
authors = ["Laurent Querel <laurent.querel@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
An ergonomic async client library for GCP BigQuery.
"""
homepage = "https://github.com/lquerel/gcp-bigquery-client"
repository = "https://github.com/lquerel/gcp-bigquery-client"
documentation = "https://docs.rs/gcp-bigquery-client"
readme = "README.md"
exclude = ["/.github/*"]
keywords = ["gcp", "bigquery", "google-cloud"]
categories = ["database"]

[features]
default = ["rust-tls"]
native-tls = ["reqwest/native-tls"]
rust-tls = ["reqwest/rustls-tls"]
# Feature used to remove cloud-storage from the standard build.
# cloud-storage has a dependency on chrono, so the feature is there to remove this dependency by default.
bq_load_job = ["cloud-storage"]

[dependencies]
yup-oauth2 = "7.0.1"
hyper = {version="0.14", features = ["http1"]}
hyper-rustls = {version="0.23.0", features = ["native-tokio"]}
thiserror = "1"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "net", "sync", "macros"] }
tokio-stream = "0.1"
async-stream = "0.3"
reqwest = { version = "0.11", default-features = false, features = ["json"] }
url = "2"
serde = "1"
serde_json = "1"
log = "0.4"
time = { version = "0.3.11", features = ["local-offset", "serde", "serde-well-known"] }
cloud-storage = {version="0.11.0", features = ["global-client"], optional = true}

[dev-dependencies]
tokio-test = "0.4"
rand = "0.8"