[package]
name = "gcp-bigquery-client"
version = "0.21.0"
authors = ["Laurent Querel <laurent.querel@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
An ergonomic async client library for GCP BigQuery.
"""
homepage = "https://github.com/lquerel/gcp-bigquery-client"
repository = "https://github.com/lquerel/gcp-bigquery-client"
documentation = "https://docs.rs/gcp-bigquery-client"
readme = "README.md"
exclude = ["/.github/*"]
keywords = ["gcp", "bigquery", "google-cloud"]
categories = ["database"]

[features]
default = ["rust-tls"]
native-tls = ["reqwest/native-tls"]
rust-tls = ["reqwest/rustls-tls"]
# Feature used to remove cloud-storage from the standard build.
# cloud-storage has a dependency on chrono, so the feature is there to remove this dependency by default.
bq_load_job = ["cloud-storage"]

[dependencies]
flate2 = "1.0"
yup-oauth2 = "10.0.1"
rustls = { version="0.23.10" }
hyper = { version = "1.3.1", features = ["http1"] }
hyper-util = { version = "0.1", default-features = false, features = ["client-legacy"] }
thiserror = "1.0.59"
tokio = { version = "1.38.0", default-features = false, features = ["rt-multi-thread", "net", "sync", "macros"] }
tokio-stream = "0.1.15"
async-stream = "0.3.5"
reqwest = { version = "0.12.4", default-features = false, features = ["json"] }
url = "2.5.0"
serde = "1.0.203"
serde_json = "1.0.117"
log = "0.4.21"
time = { version = "0.3.36", features = ["local-offset", "serde", "serde-well-known"] }
cloud-storage = {version="0.11.1", features = ["global-client"], optional = true}
async-trait = "0.1.80"
dyn-clone = "1.0.17"

[dev-dependencies]
tokio-test = "0.4.4"
rand = "0.8.5"
wiremock = "0.6.0"
tempfile = "3.10.1"
fake = "2.9.2"
